macos_min_version:             # [osx and x86_64]
  - 10.13                      # [osx and x86_64]
c_stdlib_version:              # [osx and x86_64]
  - 10.13                      # [osx and x86_64]

zip_keys:
  -
    - libboost_devel
    - libboost_python_devel

libboost_devel:
  - '1.82'
  - '1.84'
libboost_python_devel:
  - '1.82'
  - '1.84'
